I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    scene underpass day with dissolve(30)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    scene underpass day with dissolve(30)
  File "C:\Users\David\Downloads\Software Work\Renpy\renpy-6.99.8-sdk\renpy\ast.py", line 1265, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\David\Downloads\Software Work\Renpy\renpy-6.99.8-sdk\renpy\exports.py", line 1356, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\David\Downloads\Software Work\Renpy\renpy-6.99.8-sdk\renpy\display\core.py", line 1989, in do_with
    clear=clear)
  File "C:\Users\David\Downloads\Software Work\Renpy\renpy-6.99.8-sdk\renpy\display\core.py", line 2424, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "C:\Users\David\Downloads\Software Work\Renpy\renpy-6.99.8-sdk\renpy\display\core.py", line 2638, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-8-6.2.9200
Ren'Py 6.99.8.959
Prototype A 0.0
